# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Create virtual machines
  servers=[
    {
      :hostname => "VSV-01",
      :box => "ubuntu/jammy64",
      :ip => "172.16.1.11",
      :ssh_port => '22',
      :http_port => '80'
    }
  ]

  # Go trough every node for each machine stated in servers
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
      node.vm.network "forwarded_port", guest: 80, host: machine[:http_port], id: "http"
      #node.vm.synched_folder "../data", "home/vagrant/data"
      #node.vm.provision "file", source: "./copiedfile.txt", destination: "/home/vagrant/copiedfile.txt"

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 4]
      end
      
      # Update and upgrade machine
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
      SHELL

      # Install Nginx with Ansible
      node.vm.provision "shell", inline: <<-SHELL
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt update
        sudo apt install -y ansible
      SHELL
    end
  end
end