# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Create virtual machines
  servers=[
    {
      :hostname => "VSV-01",
      :box => "ubuntu/jammy64",
      :ip => "172.16.1.11",
      :ssh_port => '2201',
      :http_port => '8081'
    },
    {
      :hostname => "VSV-02",
      :box => "ubuntu/jammy64",
      :ip => "172.16.1.12",
      :ssh_port => '2202',
      :http_port => '8082'
    },
    {
      :hostname => "VSV-03",
      :box => "ubuntu/jammy64",
      :ip => "172.16.1.13",
      :ssh_port => '2203',
      :http_port => '8083'
    }
  ]

  # Go trough every node for each machine stated in servers
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
      node.vm.network "forwarded_port", guest: 80, host: machine[:http_port], id: "http"
      #node.vm.synched_folder "../data", "home/vagrant/data"
      #node.vm.provision "file", source: "./copiedfile.txt", destination: "/home/vagrant/copiedfile.txt"

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 1]
      end

      # Update and upgrade machine
      node.vm.provision "shell", inline: <<-SHELL
        echo "Updating repos"
        apt-get update
        echo "Upgrading packages"
        apt-get upgrade -y
      SHELL

      # Install Apache2, MySQL, PHP & WordPress
      node.vm.provision "shell", inline: <<-SHELL
        echo "Install Apache2"
        apt-get install -y apache2
        echo "Install MySQL"
        apt-get install -y mysql-server
        echo "Install PHP"
        apt-get install -y php php-mysql
        sudo /vagrant/mysql_setup.sh
        sudo /vagrant/apache2_setup.sh
        sudo /vagrant/wordpress_install.sh
        sudo /vagrant/wordpress_setup.sh
        sudo /vagrant/wordpress_parms.sh
      SHELL
    end
  end
end

# Sources below:  
# https://www.youtube.com/watch?v=a9pHnOkhcds&t=201s&ab_channel=DevOpsJourney
# https://moodle.zuyd.nl/mod/resource/view.php?id=1248951
# https://stackoverflow.com/questions/39951808/run-mysql-commands-in-bash-script-without-logging-in-or-adding-u-root-to-every
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-on-ubuntu-22-04-with-a-lamp-stack
